<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mwc_soccer_control</name>
  <version>0.1.0</version>
  <description>Soccer main controller for MWC robot soccer.</description>
  <maintainer email="todo@example.com">MWC Soccer Team</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>
  <depend>message_center</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <exec_depend>rclpy</exec_depend>
  <depend>unitree_sdk2</depend>
  <depend>soccer_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
